[mypy]
python_version = 3.11
files = src

check_untyped_defs = True
no_implicit_optional = True

warn_redundant_casts = True
warn_unused_ignores = True
warn_unreachable = True

show_error_codes = True
show_error_context = True
pretty = True

exclude = ^(outputs|data|\.git|\.pytest_cache|\.ruff_cache)/

[mypy-tests.*]
ignore_errors = True
