[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#1F77B4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6F8"
textColor = "#262730"
font = "sans serif"
